# DP05

In [17]:
import pandas as pd
import requests

In [44]:
metadata_url = f"https://api.census.gov/data/2023/acs/acs5/profile/variables.json"
    
# Fetch the metadata
response = requests.get(metadata_url)

if response.status_code == 200:
    # Extract the variables metadata
    metadata = response.json()
    variables = metadata["variables"]

    # Filter for DP05 group variables
    dp05_variables = {
        key: value["label"]
        for key, value in variables.items()
        if key.startswith("DP05")
    }

    # Convert to DataFrame for better visualization (optional)
    df_rename_cols = pd.DataFrame(list(dp05_variables.items()), columns=["Variable Code", "Description"])

In [45]:
df_rename_cols

    Variable Code                                        Description
0     DP05_0050PE  Percent!!RACE!!Total population!!One race!!Asi...
1     DP05_0094PE  Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
2      DP05_0028E  Estimate!!SEX AND AGE!!Total population!!18 ye...
3     DP05_0028PE  Percent!!SEX AND AGE!!Total population!!18 yea...
4     DP05_0081PE  Percent!!HISPANIC OR LATINO AND RACE!!Total po...
..            ...                                                ...
183   DP05_0010PE  Percent!!SEX AND AGE!!Total population!!25 to ...
184    DP05_0050E  Estimate!!RACE!!Total population!!One race!!As...
185    DP05_0051E  Estimate!!RACE!!Total population!!One race!!As...
186   DP05_0054PE  Percent!!RACE!!Total population!!One race!!Asi...
187   DP05_0041PE  Percent!!RACE!!Total population!!One race!!Ame...

[188 rows x 2 columns]

In [46]:
# keep row where the NAME col after _ has 5 characters and end in E
df_rename_cols = df_rename_cols[df_rename_cols["Variable Code"].str.split("_").str[1].str.len() == 5]
df_rename_cols = df_rename_cols[df_rename_cols["Variable Code"].str.split("_").str[1].str.endswith("E")]

In [55]:
# Extract proper description from the DESCRIPTION col
"""
Estimate!!SEX AND AGE!!10 to 14 years

give 10 to 14 years
"""

df_rename_cols["Description2"] = df_rename_cols["Description"].str.split("!!").str[-1]

In [65]:
df_rename_cols.to_csv("dp05_variables_estimates.csv", index=False)

In [66]:
# Dict for mapping variable code to description
variable_code_to_description = df_rename_cols.set_index("Variable Code")["Description2"].to_dict()

In [67]:
variable_code_to_description

{'DP05_0028E': 'Sex ratio (males per 100 females)',
 'DP05_0029E': '65 years and over',
 'DP05_0024E': '65 years and over',
 'DP05_0025E': '18 years and over',
 'DP05_0026E': 'Male',
 'DP05_0027E': 'Female',
 'DP05_0020E': '16 years and over',
 'DP05_0021E': '18 years and over',
 'DP05_0022E': '21 years and over',
 'DP05_0023E': '62 years and over',
 'DP05_0036E': 'One race',
 'DP05_0037E': 'White',
 'DP05_0038E': 'Black or African American',
 'DP05_0039E': 'American Indian and Alaska Native',
 'DP05_0032E': 'Sex ratio (males per 100 females)',
 'DP05_0033E': 'Total population',
 'DP05_0034E': 'One race',
 'DP05_0035E': 'Two or More Races',
 'DP05_0030E': 'Male',
 'DP05_0031E': 'Female',
 'DP05_0091E': 'Total housing units',
 'DP05_0090E': 'Two races excluding Some Other Race, and three or more races',
 'DP05_0008E': '15 to 19 years',
 'DP05_0009E': '20 to 24 years',
 'DP05_0004E': 'Sex ratio (males per 100 females)',
 'DP05_0005E': 'Under 5 years',
 'DP05_0006E': '5 to 9 years',
 'DP05_0007E': '10 to 14 years',
 'DP05_0001E': 'Total population',
 'DP05_0002E': 'Male',
 'DP05_0003E': 'Female',
 'DP05_0088E': 'Two or More Races',
 'DP05_0089E': 'Two races including Some Other Race',
 'DP05_0084E': 'American Indian and Alaska Native alone',
 'DP05_0085E': 'Asian alone',
 'DP05_0086E': 'Native Hawaiian and Other Pacific Islander alone',
 'DP05_0087E': 'Some Other Race alone',
 'DP05_0080E': 'Other Hispanic or Latino',
 'DP05_0081E': 'Not Hispanic or Latino',
 'DP05_0082E': 'White alone',
 'DP05_0083E': 'Black or African American alone',
 'DP05_0016E': '75 to 84 years',
 'DP05_0017E': '85 years and over',
 'DP05_0018E': 'Median age (years)',
 'DP05_0019E': 'Under 18 years',
 'DP05_0012E': '45 to 54 years',
 'DP05_0013E': '55 to 59 years',
 'DP05_0014E': '60 to 64 years',
 'DP05_0015E': '65 to 74 years',
 'DP05_0010E': '25 to 34 years',
 'DP05_0011E': '35 to 44 years',
 'DP05_0092E': 'Citizen, 18 and over population',
 'DP05_0093E': 'Male',
 'DP05_0094E': 'Female',
 'DP05_0068E': 'Total population',
 'DP05_0069E': 'White',
 'DP05_0064E': 'White and Asian',
 'DP05_0065E': 'White and Some Other Race',
 'DP05_0066E': 'Black or African American and American Indian and Alaska Native',
 'DP05_0067E': 'Black or African American and Some Other Race',
 'DP05_0060E': 'Some Other Race',
 'DP05_0061E': 'Two or More Races',
 'DP05_0062E': 'White and Black or African American',
 'DP05_0063E': 'White and American Indian and Alaska Native',
 'DP05_0076E': 'Hispanic or Latino (of any race)',
 'DP05_0077E': 'Mexican',
 'DP05_0078E': 'Puerto Rican',
 'DP05_0079E': 'Cuban',
 'DP05_0072E': 'Asian',
 'DP05_0073E': 'Native Hawaiian and Other Pacific Islander',
 'DP05_0074E': 'Some Other Race',
 'DP05_0075E': 'Total population',
 'DP05_0070E': 'Black or African American',
 'DP05_0071E': 'American Indian and Alaska Native',
 'DP05_0048E': 'Asian Indian',
 'DP05_0049E': 'Chinese',
 'DP05_0044E': 'Navajo Nation',
 'DP05_0045E': 'Nome Eskimo Community',
 'DP05_0046E': 'Other American Indian and Alaska Native',
 'DP05_0047E': 'Asian',
 'DP05_0040E': 'Aztec',
 'DP05_0041E': 'Blackfeet Tribe of the Blackfeet Indian Reservation of Montana',
 'DP05_0042E': 'Maya',
 'DP05_0043E': 'Native Village of Barrow Inupiat Traditional Government',
 'DP05_0056E': 'Chamorro',
 'DP05_0057E': 'Native Hawaiian',
 'DP05_0058E': 'Samoan',
 'DP05_0059E': 'Other Native Hawaiian and Other Pacific Islander',
 'DP05_0052E': 'Korean',
 'DP05_0053E': 'Vietnamese',
 'DP05_0054E': 'Other Asian',
 'DP05_0055E': 'Native Hawaiian and Other Pacific Islander',
 'DP05_0050E': 'Filipino',
 'DP05_0051E': 'Japanese'}

In [57]:
# All counties in Arkansas
# Download the data from https://api.census.gov/data/timeseries/intltrade/exports/porthsexport?get=group(IT00EXPORTSPORTHS)&E_COMMODITY=-&time=2024-10&CTY_CODE=-&ucgid=0100000US

# Fetch the data
data_url = "https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo(0400000US05$0500000)"

response = requests.get(data_url)

if response.status_code == 200:
    # Extract the data
    data = response.json()

    # Convert to DataFrame for better visualization (optional)
    df_data = pd.DataFrame(data[1:], columns=data[0])

df_data.to_csv("data_counties_arkansas.csv", index=False)

In [58]:
df_data

,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0001PE,DP05_0001PEA,DP05_0001PM,DP05_0001PMA,DP05_0002E,DP05_0002EA,...,DP05_0094EA,DP05_0094M,DP05_0094MA,DP05_0094PE,DP05_0094PEA,DP05_0094PM,DP05_0094PMA,GEO_ID,NAME,ucgid
0,16773,None,-555555555,*****,16773,None,-888888888,(X),8198,None,...,None,71,None,52.1,None,0.5,None,0500000US05001,"Arkansas County, Arkansas",0500000US05001
1,18722,None,-555555555,*****,18722,None,-888888888,(X),8864,None,...,None,83,None,53.1,None,0.3,None,0500000US05003,"Ashley County, Arkansas",0500000US05003
2,42150,None,-555555555,*****,42150,None,-888888888,(X),20534,None,...,None,152,None,51.7,None,0.3,None,0500000US05005,"Baxter County, Arkansas",0500000US05005
3,294541,None,-555555555,*****,294541,None,-888888888,(X),147765,None,...,None,646,None,50.7,None,0.2,None,0500000US05007,"Benton County, Arkansas",0500000US05007
4,37896,None,-555555555,*****,37896,None,-888888888,(X),18598,None,...,None,143,None,51.4,None,0.3,None,0500000US05009,"Boone County, Arkansas",0500000US05009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,15936,None,-555555555,*****,15936,None,-888888888,(X),8001,None,...,None,94,None,51.0,None,0.6,None,0500000US05141,"Van Buren County, Arkansas",0500000US05141
71,251863,None,-555555555,*****,251863,None,-888888888,(X),126651,None,...,None,646,None,50.6,None,0.2,None,0500000US05143,"Washington County, Arkansas",0500000US05143
72,77395,None,-555555555,*****,77395,None,-888888888,(X),37828,None,...,None,161,None,52.3,None,0.2,None,0500000US05145,"White County, Arkansas",0500000US05145
73,6157,None,-555555555,*****,6157,None,-888888888,(X),3149,None,...,None,4,None,52.0,None,0.3,None,0500000US05147,"Woodruff County, Arkansas",0500000US05147
74,20195,None,-555555555,*****,20195,None,-888888888,(X),10241,None,...,None,166,None,50.0,None,0.7,None,0500000US05149,"Yell County, Arkansas",0500000US05149

In [59]:
# Fetch counties and GEOID
df_data_counties = df_data[["NAME", "GEO_ID"]]

In [60]:
df_data_counties

                           NAME          GEO_ID
0     Arkansas County, Arkansas  0500000US05001
1       Ashley County, Arkansas  0500000US05003
2       Baxter County, Arkansas  0500000US05005
3       Benton County, Arkansas  0500000US05007
4        Boone County, Arkansas  0500000US05009
..                          ...             ...
70   Van Buren County, Arkansas  0500000US05141
71  Washington County, Arkansas  0500000US05143
72       White County, Arkansas  0500000US05145
73    Woodruff County, Arkansas  0500000US05147
74        Yell County, Arkansas  0500000US05149

[75 rows x 2 columns]

In [61]:
# Download the data from https://api.census.gov/data/timeseries/intltrade/exports/porthsexport?get=group(IT00EXPORTSPORTHS)&E_COMMODITY=-&time=2024-10&CTY_CODE=-&ucgid=0100000US

# Fetch the data
data_url = "https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo(0500000US05001$8600000)"

response = requests.get(data_url)

if response.status_code == 200:
    # Extract the data
    data = response.json()

    # Convert to DataFrame for better visualization (optional)
    df_data2 = pd.DataFrame(data[1:], columns=data[0])

In [62]:
df_data2

,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0001PE,DP05_0001PEA,DP05_0001PM,DP05_0001PMA,DP05_0002E,DP05_0002EA,...,DP05_0094EA,DP05_0094M,DP05_0094MA,DP05_0094PE,DP05_0094PEA,DP05_0094PM,DP05_0094PMA,GEO_ID,NAME,ucgid
0,859,None,178,None,859,None,-888888888,(X),378,None,...,None,78,None,49.9,None,6.8,None,860Z200US72003,ZCTA5 72003,860Z200US72003
1,691,None,226,None,691,None,-888888888,(X),413,None,...,None,79,None,43.1,None,9.6,None,860Z200US72004,ZCTA5 72004,860Z200US72004
2,200,None,85,None,200,None,-888888888,(X),112,None,...,None,37,None,43.5,None,13.6,None,860Z200US72026,ZCTA5 72026,860Z200US72026
3,79,None,81,None,79,None,-888888888,(X),43,None,...,None,39,None,45.6,None,12.9,None,860Z200US72038,ZCTA5 72038,860Z200US72038
4,4956,None,339,None,4956,None,-888888888,(X),2444,None,...,None,205,None,53.4,None,3.3,None,860Z200US72042,ZCTA5 72042,860Z200US72042
5,57,None,43,None,57,None,-888888888,(X),26,None,...,None,23,None,54.4,None,10.4,None,860Z200US72048,ZCTA5 72048,860Z200US72048
6,567,None,173,None,567,None,-888888888,(X),237,None,...,None,69,None,53.3,None,9.8,None,860Z200US72055,ZCTA5 72055,860Z200US72055
7,862,None,213,None,862,None,-888888888,(X),508,None,...,None,81,None,48.4,None,7.3,None,860Z200US72073,ZCTA5 72073,860Z200US72073
8,543,None,208,None,543,None,-888888888,(X),308,None,...,None,73,None,46.4,None,6.6,None,860Z200US72134,ZCTA5 72134,860Z200US72134
9,325,None,128,None,325,None,-888888888,(X),215,None,...,None,46,None,46.0,None,11.0,None,860Z200US72140,ZCTA5 72140,860Z200US72140
10,8895,None,236,None,8895,None,-888888888,(X),4281,None,...,None,198,None,51.8,None,2.1,None,860Z200US72160,ZCTA5 72160,860Z200US72160
11,219,None,90,None,219,None,-888888888,(X),110,None,...,None,40,None,51.7,None,6.0,None,860Z200US72166,ZCTA5 72166,860Z200US72166
12,425,None,252,None,425,None,-888888888,(X),192,None,...,None,133,None,63.8,None,15.2,None,860Z200US72175,ZCTA5 72175,860Z200US72175

In [63]:
df_data2.columns

Index(['DP05_0001E', 'DP05_0001EA', 'DP05_0001M', 'DP05_0001MA', 'DP05_0001PE',
       'DP05_0001PEA', 'DP05_0001PM', 'DP05_0001PMA', 'DP05_0002E',
       'DP05_0002EA',
       ...
       'DP05_0094EA', 'DP05_0094M', 'DP05_0094MA', 'DP05_0094PE',
       'DP05_0094PEA', 'DP05_0094PM', 'DP05_0094PMA', 'GEO_ID', 'NAME',
       'ucgid'],
      dtype='object', length=755)

In [64]:
df_data2['DP05_0072E']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10    14
11     0
12     0
Name: DP05_0072E, dtype: object

In [ ]:
# Write a function that takes in state, finds all counties, then find all zip codes in each county

def get_counties(state):
    data_url = f"https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo(0400000US{state}$0500000)"
    response = requests.get(data_url)
    if response.status_code == 200:
        data = response.json()
        df_data = pd.DataFrame(data[1:], columns=data[0])
    return df_data

def get_zip_codes(state, county):
    data_url = f"https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo(0500000US{state}{county}$8600000)"
    response = requests.get(data_url)
    if response.status_code == 200:
        data = response.json()
        df_data = pd.DataFrame(data[1:], columns=data[0])
    return df_data

In [85]:
import requests
import pandas as pd

# Function to get counties in a given state
def get_counties(state):
    data_url = f"https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo(0400000US{state}$0500000)"
    response = requests.get(data_url)
    if response.status_code == 200:
        data = response.json()
        df_data = pd.DataFrame(data[1:], columns=data[0])
        return df_data[["NAME", "GEO_ID"]]
    else:
        print(f"Error fetching counties for state {state}: {response.status_code}")
        return pd.DataFrame()  # Return empty DataFrame in case of error

# Function to get zip codes in a given state and county
def get_zip_codes(state, county_code):
    data_url = f"https://api.census.gov/data/2023/acs/acs5/profile?get=group(DP05)&ucgid=pseudo({county_code}$8600000)"
    response = requests.get(data_url)
    if response.status_code == 200:
        data = response.json()
        df_data = pd.DataFrame(data[1:], columns=data[0])
        return df_data
    else:
        print(f"Error fetching zip codes for county {county_code} in state {state}: {response.status_code}")
        return pd.DataFrame()  # Return empty DataFrame in case of error

# Function to aggregate data for all zip codes in all counties of a state
def collect_zipcode_data(state):
    # Get all counties in the state
    counties_df = get_counties(state)
    if counties_df.empty:
        return pd.DataFrame()  # Return empty if no counties were found
    
    final_df = pd.DataFrame()  # DataFrame to store the final result

    # Iterate over each county in the state
    for index, row in counties_df.iterrows():
        county = row['NAME']  # Extract county ID from the row (adjust based on your actual data structure)
        county_code = row['GEO_ID']  # Extract county code from the row (adjust based on your actual data structure)
        print(f"Fetching data for county: {county_code} - {county}")
        
        # Get zip codes for the county
        zip_codes_df = get_zip_codes(state, county_code)
        if not zip_codes_df.empty:
            # Add county and state information to the zip code data
            zip_codes_df['County'] = county
            zip_codes_df['County Code'] = county_code
            zip_codes_df['State'] = state
            final_df = pd.concat([final_df, zip_codes_df], ignore_index=True)
    
    return final_df

# Example: Collect data for a given state (e.g., state '37' for North Carolina)
state = '37'  # Replace with the state FIPS code you want to query
zipcode_data = collect_zipcode_data(state)

# Display or save the collected data
print(zipcode_data.head())
#zipcode_data.to_csv("zipcode_data.csv", index=False)  # Optionally save to CSV

Fetching data for county: 0500000US37001 - Alamance County, North Carolina
Fetching data for county: 0500000US37003 - Alexander County, North Carolina
Fetching data for county: 0500000US37005 - Alleghany County, North Carolina
Fetching data for county: 0500000US37007 - Anson County, North Carolina
Fetching data for county: 0500000US37009 - Ashe County, North Carolina
Fetching data for county: 0500000US37011 - Avery County, North Carolina
Fetching data for county: 0500000US37013 - Beaufort County, North Carolina
Fetching data for county: 0500000US37015 - Bertie County, North Carolina
Fetching data for county: 0500000US37017 - Bladen County, North Carolina
Fetching data for county: 0500000US37019 - Brunswick County, North Carolina
Fetching data for county: 0500000US37021 - Buncombe County, North Carolina
Fetching data for county: 0500000US37023 - Burke County, North Carolina
Fetching data for county: 0500000US37025 - Cabarrus County, North Carolina
Fetching data for county: 0500000US37027 - Caldwell County, North Carolina
Fetching data for county: 0500000US37029 - Camden County, North Carolina
Fetching data for county: 0500000US37031 - Carteret County, North Carolina
Fetching data for county: 0500000US37033 - Caswell County, North Carolina
Fetching data for county: 0500000US37035 - Catawba County, North Carolina
Fetching data for county: 0500000US37037 - Chatham County, North Carolina
Fetching data for county: 0500000US37039 - Cherokee County, North Carolina
Fetching data for county: 0500000US37041 - Chowan County, North Carolina
Fetching data for county: 0500000US37043 - Clay County, North Carolina
Fetching data for county: 0500000US37045 - Cleveland County, North Carolina
Fetching data for county: 0500000US37047 - Columbus County, North Carolina
Fetching data for county: 0500000US37049 - Craven County, North Carolina
Fetching data for county: 0500000US37051 - Cumberland County, North Carolina
Fetching data for county: 0500000US37053 - Currituck County, North Carolina
Fetching data for county: 0500000US37055 - Dare County, North Carolina
Fetching data for county: 0500000US37057 - Davidson County, North Carolina
Fetching data for county: 0500000US37059 - Davie County, North Carolina
Fetching data for county: 0500000US37061 - Duplin County, North Carolina
Fetching data for county: 0500000US37063 - Durham County, North Carolina
Fetching data for county: 0500000US37065 - Edgecombe County, North Carolina
Fetching data for county: 0500000US37067 - Forsyth County, North Carolina
Fetching data for county: 0500000US37069 - Franklin County, North Carolina
Fetching data for county: 0500000US37071 - Gaston County, North Carolina
Fetching data for county: 0500000US37073 - Gates County, North Carolina
Fetching data for county: 0500000US37075 - Graham County, North Carolina
Fetching data for county: 0500000US37077 - Granville County, North Carolina
Fetching data for county: 0500000US37079 - Greene County, North Carolina
Fetching data for county: 0500000US37081 - Guilford County, North Carolina
Fetching data for county: 0500000US37083 - Halifax County, North Carolina
Fetching data for county: 0500000US37085 - Harnett County, North Carolina
Fetching data for county: 0500000US37087 - Haywood County, North Carolina
Fetching data for county: 0500000US37089 - Henderson County, North Carolina
Fetching data for county: 0500000US37091 - Hertford County, North Carolina
Fetching data for county: 0500000US37093 - Hoke County, North Carolina
Fetching data for county: 0500000US37095 - Hyde County, North Carolina
Fetching data for county: 0500000US37097 - Iredell County, North Carolina
Fetching data for county: 0500000US37099 - Jackson County, North Carolina
Fetching data for county: 0500000US37101 - Johnston County, North Carolina
Fetching data for county: 0500000US37103 - Jones County, North Carolina
Fetching data for county: 0500000US37105 - Lee County, North Carolina
Fetching data for county: 0500000US37107 - Lenoir County, North Carolina
Fetching data for county: 0500000US37109 - Lincoln County, North Carolina
Fetching data for county: 0500000US37111 - McDowell County, North Carolina
Fetching data for county: 0500000US37113 - Macon County, North Carolina
Fetching data for county: 0500000US37115 - Madison County, North Carolina
Fetching data for county: 0500000US37117 - Martin County, North Carolina
Fetching data for county: 0500000US37119 - Mecklenburg County, North Carolina
Fetching data for county: 0500000US37121 - Mitchell County, North Carolina
Fetching data for county: 0500000US37123 - Montgomery County, North Carolina
Fetching data for county: 0500000US37125 - Moore County, North Carolina
Fetching data for county: 0500000US37127 - Nash County, North Carolina
Fetching data for county: 0500000US37129 - New Hanover County, North Carolina
Fetching data for county: 0500000US37131 - Northampton County, North Carolina
Fetching data for county: 0500000US37133 - Onslow County, North Carolina
Fetching data for county: 0500000US37135 - Orange County, North Carolina
Fetching data for county: 0500000US37137 - Pamlico County, North Carolina
Fetching data for county: 0500000US37139 - Pasquotank County, North Carolina
Fetching data for county: 0500000US37141 - Pender County, North Carolina
Fetching data for county: 0500000US37143 - Perquimans County, North Carolina
Fetching data for county: 0500000US37145 - Person County, North Carolina
Fetching data for county: 0500000US37147 - Pitt County, North Carolina
Fetching data for county: 0500000US37149 - Polk County, North Carolina
Fetching data for county: 0500000US37151 - Randolph County, North Carolina
Fetching data for county: 0500000US37153 - Richmond County, North Carolina
Fetching data for county: 0500000US37155 - Robeson County, North Carolina
Fetching data for county: 0500000US37157 - Rockingham County, North Carolina
Fetching data for county: 0500000US37159 - Rowan County, North Carolina
Fetching data for county: 0500000US37161 - Rutherford County, North Carolina
Fetching data for county: 0500000US37163 - Sampson County, North Carolina
Fetching data for county: 0500000US37165 - Scotland County, North Carolina
Fetching data for county: 0500000US37167 - Stanly County, North Carolina
Fetching data for county: 0500000US37169 - Stokes County, North Carolina
Fetching data for county: 0500000US37171 - Surry County, North Carolina
Fetching data for county: 0500000US37173 - Swain County, North Carolina
Fetching data for county: 0500000US37175 - Transylvania County, North Carolina
Fetching data for county: 0500000US37177 - Tyrrell County, North Carolina
Fetching data for county: 0500000US37179 - Union County, North Carolina
Fetching data for county: 0500000US37181 - Vance County, North Carolina
Fetching data for county: 0500000US37183 - Wake County, North Carolina
Fetching data for county: 0500000US37185 - Warren County, North Carolina
Fetching data for county: 0500000US37187 - Washington County, North Carolina
Fetching data for county: 0500000US37189 - Watauga County, North Carolina
Fetching data for county: 0500000US37191 - Wayne County, North Carolina
Fetching data for county: 0500000US37193 - Wilkes County, North Carolina
Fetching data for county: 0500000US37195 - Wilson County, North Carolina
Fetching data for county: 0500000US37197 - Yadkin County, North Carolina
Fetching data for county: 0500000US37199 - Yancey County, North Carolina
  DP05_0001E DP05_0001EA DP05_0001M DP05_0001MA DP05_0001PE DP05_0001PEA  \
0        135        None         74        None         135         None
1        125        None        184        None         125         None
2      45967        None       1675        None       45967         None
3      40561        None       1727        None       40561         None
4      16652        None        922        None       16652         None

  DP05_0001PM DP05_0001PMA DP05_0002E DP05_0002EA  ... DP05_0094PE  \
0  -888888888          (X)         72        None  ...        50.5
1  -888888888          (X)         88        None  ...        55.2
2  -888888888          (X)      22063        None  ...        54.1
3  -888888888          (X)      20047        None  ...        52.7
4  -888888888          (X)       7648        None  ...        54.5

  DP05_0094PEA DP05_0094PM DP05_0094PMA          GEO_ID         NAME  \
0         None        10.6         None  860Z200US27201  ZCTA5 27201
1         None         7.7         None  860Z200US27202  ZCTA5 27202
2         None         1.5         None  860Z200US27215  ZCTA5 27215
3         None         1.8         None  860Z200US27217  ZCTA5 27217
4         None         2.6         None  860Z200US27244  ZCTA5 27244

            ucgid                           County     County Code State
0  860Z200US27201  Alamance County, North Carolina  0500000US37001    37
1  860Z200US27202  Alamance County, North Carolina  0500000US37001    37
2  860Z200US27215  Alamance County, North Carolina  0500000US37001    37
3  860Z200US27217  Alamance County, North Carolina  0500000US37001    37
4  860Z200US27244  Alamance County, North Carolina  0500000US37001    37

[5 rows x 758 columns]

In [86]:
zipcode_data

,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0001PE,DP05_0001PEA,DP05_0001PM,DP05_0001PMA,DP05_0002E,DP05_0002EA,...,DP05_0094PE,DP05_0094PEA,DP05_0094PM,DP05_0094PMA,GEO_ID,NAME,ucgid,County,County Code,State
0,135,None,74,None,135,None,-888888888,(X),72,None,...,50.5,None,10.6,None,860Z200US27201,ZCTA5 27201,860Z200US27201,"Alamance County, North Carolina",0500000US37001,37
1,125,None,184,None,125,None,-888888888,(X),88,None,...,55.2,None,7.7,None,860Z200US27202,ZCTA5 27202,860Z200US27202,"Alamance County, North Carolina",0500000US37001,37
2,45967,None,1675,None,45967,None,-888888888,(X),22063,None,...,54.1,None,1.5,None,860Z200US27215,ZCTA5 27215,860Z200US27215,"Alamance County, North Carolina",0500000US37001,37
3,40561,None,1727,None,40561,None,-888888888,(X),20047,None,...,52.7,None,1.8,None,860Z200US27217,ZCTA5 27217,860Z200US27217,"Alamance County, North Carolina",0500000US37001,37
4,16652,None,922,None,16652,None,-888888888,(X),7648,None,...,54.5,None,2.6,None,860Z200US27244,ZCTA5 27244,860Z200US27244,"Alamance County, North Carolina",0500000US37001,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,16621,None,406,None,16621,None,-888888888,(X),8240,None,...,51.1,None,0.9,None,860Z200US28714,ZCTA5 28714,860Z200US28714,"Yancey County, North Carolina",0500000US37199,37
1290,1872,None,389,None,1872,None,-888888888,(X),788,None,...,61.2,None,6.7,None,860Z200US28740,ZCTA5 28740,860Z200US28740,"Yancey County, North Carolina",0500000US37199,37
1291,9897,None,773,None,9897,None,-888888888,(X),5180,None,...,49.7,None,2.6,None,860Z200US28754,ZCTA5 28754,860Z200US28754,"Yancey County, North Carolina",0500000US37199,37
1292,0,None,14,None,0,None,-888888888,(X),0,None,...,-666666666.0,-,-222222222.0,**,860Z200US28755,ZCTA5 28755,860Z200US28755,"Yancey County, North Carolina",0500000US37199,37
1293,10368,None,644,None,10368,None,-888888888,(X),6169,None,...,37.8,None,2.4,None,860Z200US28777,ZCTA5 28777,860Z200US28777,"Yancey County, North Carolina",0500000US37199,37

In [87]:
# columns starting with DP05 check if len is 5 and ends with E in zipcode_data
temp = zipcode_data.columns
temp = temp[temp.str.startswith("DP05")]
temp = temp[temp.str.split("_").str[1].str.len() == 5]
temp = temp[temp.str.split("_").str[1].str.endswith("E")]

# add columns that dont start with DP05
temp = temp.append(zipcode_data.columns[~zipcode_data.columns.str.startswith("DP05")])

In [88]:
temp

Index(['DP05_0001E', 'DP05_0002E', 'DP05_0003E', 'DP05_0004E', 'DP05_0005E',
       'DP05_0006E', 'DP05_0007E', 'DP05_0008E', 'DP05_0009E', 'DP05_0010E',
       'DP05_0011E', 'DP05_0012E', 'DP05_0013E', 'DP05_0014E', 'DP05_0015E',
       'DP05_0016E', 'DP05_0017E', 'DP05_0018E', 'DP05_0019E', 'DP05_0020E',
       'DP05_0021E', 'DP05_0022E', 'DP05_0023E', 'DP05_0024E', 'DP05_0025E',
       'DP05_0026E', 'DP05_0027E', 'DP05_0028E', 'DP05_0029E', 'DP05_0030E',
       'DP05_0031E', 'DP05_0032E', 'DP05_0033E', 'DP05_0034E', 'DP05_0035E',
       'DP05_0036E', 'DP05_0037E', 'DP05_0038E', 'DP05_0039E', 'DP05_0040E',
       'DP05_0041E', 'DP05_0042E', 'DP05_0043E', 'DP05_0044E', 'DP05_0045E',
       'DP05_0046E', 'DP05_0047E', 'DP05_0048E', 'DP05_0049E', 'DP05_0050E',
       'DP05_0051E', 'DP05_0052E', 'DP05_0053E', 'DP05_0054E', 'DP05_0055E',
       'DP05_0056E', 'DP05_0057E', 'DP05_0058E', 'DP05_0059E', 'DP05_0060E',
       'DP05_0061E', 'DP05_0062E', 'DP05_0063E', 'DP05_0064E', 'DP05_0065E',
       'DP05_0066E', 'DP05_0067E', 'DP05_0068E', 'DP05_0069E', 'DP05_0070E',
       'DP05_0071E', 'DP05_0072E', 'DP05_0073E', 'DP05_0074E', 'DP05_0075E',
       'DP05_0076E', 'DP05_0077E', 'DP05_0078E', 'DP05_0079E', 'DP05_0080E',
       'DP05_0081E', 'DP05_0082E', 'DP05_0083E', 'DP05_0084E', 'DP05_0085E',
       'DP05_0086E', 'DP05_0087E', 'DP05_0088E', 'DP05_0089E', 'DP05_0090E',
       'DP05_0091E', 'DP05_0092E', 'DP05_0093E', 'DP05_0094E', 'GEO_ID',
       'NAME', 'ucgid', 'County', 'County Code', 'State'],
      dtype='object')

In [89]:
# filter zipcode_data with temp
zipcode_data = zipcode_data[temp]

In [90]:
# map the columns that start with DP05 to the description
zipcode_data = zipcode_data.rename(columns=variable_code_to_description)

In [94]:
zipcode_data

,Total population,Male,Female,Sex ratio (males per 100 females),Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 34 years,...,Total housing units,"Citizen, 18 and over population",Male,Female,GEO_ID,NAME,ucgid,County,County Code,State
0,135,72,63,114.3,0,16,22,0,0,14,...,55,97,48,49,860Z200US27201,ZCTA5 27201,860Z200US27201,"Alamance County, North Carolina",0500000US37001,37
1,125,88,37,237.8,58,0,0,0,67,0,...,30,67,30,37,860Z200US27202,ZCTA5 27202,860Z200US27202,"Alamance County, North Carolina",0500000US37001,37
2,45967,22063,23904,92.3,2759,2836,3325,2173,2005,5563,...,21854,33717,15486,18231,860Z200US27215,ZCTA5 27215,860Z200US27215,"Alamance County, North Carolina",0500000US37001,37
3,40561,20047,20514,97.7,2847,2769,3514,3271,2434,5314,...,16392,25587,12099,13488,860Z200US27217,ZCTA5 27217,860Z200US27217,"Alamance County, North Carolina",0500000US37001,37
4,16652,7648,9004,84.9,399,391,1086,3121,3166,962,...,5740,13866,6315,7551,860Z200US27244,ZCTA5 27244,860Z200US27244,"Alamance County, North Carolina",0500000US37001,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,16621,8240,8381,98.3,875,798,979,890,726,1854,...,9719,12999,6353,6646,860Z200US28714,ZCTA5 28714,860Z200US28714,"Yancey County, North Carolina",0500000US37199,37
1290,1872,788,1084,72.7,97,68,49,84,55,127,...,1308,1625,630,995,860Z200US28740,ZCTA5 28740,860Z200US28740,"Yancey County, North Carolina",0500000US37199,37
1291,9897,5180,4717,109.8,318,543,299,866,809,1542,...,4460,8309,4180,4129,860Z200US28754,ZCTA5 28754,860Z200US28754,"Yancey County, North Carolina",0500000US37199,37
1292,0,0,0,-666666666.0,0,0,0,0,0,0,...,0,0,0,0,860Z200US28755,ZCTA5 28755,860Z200US28755,"Yancey County, North Carolina",0500000US37199,37
1293,10368,6169,4199,146.9,520,551,326,388,419,1566,...,4949,8267,5141,3126,860Z200US28777,ZCTA5 28777,860Z200US28777,"Yancey County, North Carolina",0500000US37199,37

In [2]:
# Check the df
import pandas as pd

df = pd.read_csv(r"D:\UofT\Work\innovo\us_census\sample_data\zipcode_data_2023_02.csv")

In [9]:
import re

columns = df.columns.to_list()
df.columns

Index(['Total population', 'Male', 'Female',
       'Sex ratio (males per 100 females)', 'Under 5 years', '5 to 9 years',
       '10 to 14 years', '15 to 19 years', '20 to 24 years', '25 to 34 years',
       '35 to 44 years', '45 to 54 years', '55 to 59 years', '60 to 64 years',
       '65 to 74 years', '75 to 84 years', '85 years and over',
       'Median age (years)', 'Under 18 years', '16 years and over',
       '18 years and over', '21 years and over', '62 years and over',
       '65 years and over', 'One race', 'Two or More Races', 'White',
       'Black or African American', 'American Indian and Alaska Native',
       'Aztec',
       'Blackfeet Tribe of the Blackfeet Indian Reservation of Montana',
       'Maya', 'Native Village of Barrow Inupiat Traditional Government',
       'Navajo Nation', 'Nome Eskimo Community',
       'Other American Indian and Alaska Native', 'Asian', 'Asian Indian',
       'Chinese', 'Filipino', 'Japanese', 'Korean', 'Vietnamese',
       'Other Asian', 'Native Hawaiian and Other Pacific Islander', 'Chamorro',
       'Native Hawaiian', 'Samoan',
       'Other Native Hawaiian and Other Pacific Islander', 'Some Other Race',
       'White and Black or African American',
       'White and American Indian and Alaska Native', 'White and Asian',
       'White and Some Other Race',
       'Black or African American and American Indian and Alaska Native',
       'Black or African American and Some Other Race',
       'Hispanic or Latino (of any race)', 'Mexican', 'Puerto Rican', 'Cuban',
       'Other Hispanic or Latino', 'Not Hispanic or Latino', 'White alone',
       'Black or African American alone',
       'American Indian and Alaska Native alone', 'Asian alone',
       'Native Hawaiian and Other Pacific Islander alone',
       'Some Other Race alone', 'Two races including Some Other Race',
       'Two races excluding Some Other Race, and three or more races',
       'Total housing units', 'Citizen, 18 and over population', 'GEO_ID',
       'Zip Code', 'ucgid', 'County', 'County Code', 'State Number', 'State',
       'Year'],
      dtype='object')

In [12]:
# Classify gender-related columns
gender_male = []
gender_female = []
gender_ratio = []

for col in columns:
    col_lower = col.lower()
    # Direct Male/Female columns
    if 'ratio' in col_lower:
        gender_male.append(col)
    elif 'female' in col_lower:
        gender_female.append(col)
    # Gender Ratio columns
    elif 'male' in col_lower:
        gender_ratio.append(col)

print("Male Columns:", gender_male)
print("Female Columns:", gender_female)
print("Gender Ratio Columns:", gender_ratio)

Male Columns: ['Sex ratio (males per 100 females)']
Female Columns: ['Female']
Gender Ratio Columns: ['Male']

In [10]:
# Classify age-related columns
age_brackets = []
age_groups = []
age_overall = []
age_citizen = []

for col in columns:
    # Rule: Age Bracket (has "X to Y years" pattern)
    if 'Citizen' in col:
        age_citizen.append(col)
    elif re.search(r'\d+\s*to\s*\d+\s*years', col):
        age_brackets.append(col)
    # Rule: Age Group (contains "under", "and over", or specific keywords)
    elif any(keyword in col.lower() for keyword in ['under', 'and over']):
        age_groups.append(col)
    elif 'Median age' in col:
        age_overall.append(col)

print("Age Brackets:", age_brackets)
print("Age Groups:", age_groups)
print("Overall Age:", age_overall)
print("Citizens Age:", age_citizen)

Age Brackets: ['5 to 9 years', '10 to 14 years', '15 to 19 years', '20 to 24 years', '25 to 34 years', '35 to 44 years', '45 to 54 years', '55 to 59 years', '60 to 64 years', '65 to 74 years', '75 to 84 years']
Age Groups: ['Under 5 years', '85 years and over', 'Under 18 years', '16 years and over', '18 years and over', '21 years and over', '62 years and over', '65 years and over']
Overall Age: ['Median age (years)']
Citizens Age: ['Citizen, 18 and over population']

In [13]:
# Race and ethnicity categories
single_race = []
asian_subcategories = []
mixed_race = []
native_american_indigenous = []
hispanic_ethnicity = []
general_race = []

# Mapping logic
for col in columns:
    col_lower = col.lower()
    
    # Standard single race
    if any(race in col_lower for race in ['white', 'black or african american', 'native hawaiian']):
        single_race.append(col)

    # Asian subcategories
    elif any(asian_group in col_lower for asian_group in ['asian indian', 'chinese', 'filipino', 'japanese', 'korean', 'vietnamese', 'other asian']):
        asian_subcategories.append(col)
    
    # Mixed race categories
    elif 'and' in col_lower or 'two races' in col_lower or 'three' in col_lower:
        mixed_race.append(col)
    
    # Native American or Indigenous groups
    elif any(group in col_lower for group in ['american indian', 'alaska native', 'aztec', 'navajo', 'blackfeet', 'inupiat', 'maya']):
        native_american_indigenous.append(col)
    
    # Hispanic or Latino categories
    elif any(term in col_lower for term in ['hispanic', 'latino', 'mexican', 'puerto rican', 'cuban']):
        hispanic_ethnicity.append(col)
    
    # General categories
    else:
        general_race.append(col)

# Display categorized results
print("Single Race Categories:", single_race)
print("Asian Subcategories:", asian_subcategories)
print("Mixed Race Categories:", mixed_race)
print("Native American/Indigenous Groups:", native_american_indigenous)
print("Hispanic/Latino Categories:", hispanic_ethnicity)
print("General Race Categories:", general_race)

Single Race Categories: ['White', 'Black or African American', 'Native Hawaiian and Other Pacific Islander', 'Native Hawaiian', 'Other Native Hawaiian and Other Pacific Islander', 'White and Black or African American', 'White and American Indian and Alaska Native', 'White and Asian', 'White and Some Other Race', 'Black or African American and American Indian and Alaska Native', 'Black or African American and Some Other Race', 'White alone', 'Black or African American alone', 'Native Hawaiian and Other Pacific Islander alone']
Asian Subcategories: ['Asian Indian', 'Chinese', 'Filipino', 'Japanese', 'Korean', 'Vietnamese', 'Other Asian']
Mixed Race Categories: ['85 years and over', '16 years and over', '18 years and over', '21 years and over', '62 years and over', '65 years and over', 'American Indian and Alaska Native', 'Other American Indian and Alaska Native', 'American Indian and Alaska Native alone', 'Two races including Some Other Race', 'Two races excluding Some Other Race, and three or more races', 'Citizen, 18 and over population']
Native American/Indigenous Groups: ['Aztec', 'Blackfeet Tribe of the Blackfeet Indian Reservation of Montana', 'Maya', 'Native Village of Barrow Inupiat Traditional Government', 'Navajo Nation']
Hispanic/Latino Categories: ['Hispanic or Latino (of any race)', 'Mexican', 'Puerto Rican', 'Cuban', 'Other Hispanic or Latino', 'Not Hispanic or Latino']
General Race Categories: ['Total population', 'Male', 'Female', 'Sex ratio (males per 100 females)', 'Under 5 years', '5 to 9 years', '10 to 14 years', '15 to 19 years', '20 to 24 years', '25 to 34 years', '35 to 44 years', '45 to 54 years', '55 to 59 years', '60 to 64 years', '65 to 74 years', '75 to 84 years', 'Median age (years)', 'Under 18 years', 'One race', 'Two or More Races', 'Nome Eskimo Community', 'Asian', 'Chamorro', 'Samoan', 'Some Other Race', 'Asian alone', 'Some Other Race alone', 'Total housing units', 'GEO_ID', 'Zip Code', 'ucgid', 'County', 'County Code', 'State Number', 'State', 'Year']

In [14]:
total_housing_units = ['Total housing units']

In [ ]:
# Create a dictionary to map types
category_mapping = {
    **{col: "Single Race" for col in single_race},
    **{col: "Asian Subcategory" for col in asian_subcategories},
    **{col: "Mixed Race" for col in mixed_race},
    **{col: "Native American/Indigenous" for col in native_american_indigenous},
    **{col: "Hispanic/Latino" for col in hispanic_ethnicity},
    **{col: "General Race" for col in general_race},
    **{col: "Total Housing Units" for col in total_housing_units},
    
}

In [4]:
melted_df = df.melt(id_vars=['GEO_ID', 'Zip Code', 'ucgid', 'County', 'County Code', 'State Number', 'State',
       'Year'], var_name='Category', value_name='Population')

In [5]:
melted_df

,GEO_ID,Zip Code,ucgid,County,County Code,State Number,State,Year,Category,Population
0,860Z200US99553,99553,860Z200US99553,Aleutians East Borough,0500000US02013,2,Alaska,2023,Total population,737.0
1,860Z200US99571,99571,860Z200US99571,Aleutians East Borough,0500000US02013,2,Alaska,2023,Total population,236.0
2,860Z200US99583,99583,860Z200US99583,Aleutians East Borough,0500000US02013,2,Alaska,2023,Total population,95.0
3,860Z200US99612,99612,860Z200US99612,Aleutians East Borough,0500000US02013,2,Alaska,2023,Total population,1204.0
4,860Z200US99661,99661,860Z200US99661,Aleutians East Borough,0500000US02013,2,Alaska,2023,Total population,1151.0
...,...,...,...,...,...,...,...,...,...,...
18571,860Z200US99774,99774,860Z200US99774,Yukon-Koyukuk Census Area,0500000US02290,2,Alaska,2023,"Citizen, 18 and over population",7.0
18572,860Z200US99777,99777,860Z200US99777,Yukon-Koyukuk Census Area,0500000US02290,2,Alaska,2023,"Citizen, 18 and over population",215.0
18573,860Z200US99781,99781,860Z200US99781,Yukon-Koyukuk Census Area,0500000US02290,2,Alaska,2023,"Citizen, 18 and over population",89.0
18574,860Z200US99788,99788,860Z200US99788,Yukon-Koyukuk Census Area,0500000US02290,2,Alaska,2023,"Citizen, 18 and over population",67.0
18575,860Z200US99790,99790,860Z200US99790,Yukon-Koyukuk Census Area,0500000US02290,2,Alaska,2023,"Citizen, 18 and over population",11.0

# S1901

In [21]:
import pandas as pd
df_income = pd.read_csv(r"D:\UofT\Work\innovo\us_census\reference_files\USE_INCOME_MAPPING.csv")

In [22]:
df_income

                Name                                              Label
0     S1901_C01_001E                        Estimate!!Households!!Total
1    S1901_C01_001EA          Annotation of Estimate!!Households!!Total
2     S1901_C01_001M                 Margin of Error!!Households!!Total
3    S1901_C01_001MA   Annotation of Margin of Error!!Households!!Total
4     S1901_C01_002E     Estimate!!Households!!Total!!Less than $10,000
..               ...                                                ...
251  S1901_C04_015MA  Annotation of Margin of Error!!Nonfamily house...
252   S1901_C04_016E  Estimate!!Nonfamily households!!PERCENT ALLOCA...
253  S1901_C04_016EA  Annotation of Estimate!!Nonfamily households!!...
254   S1901_C04_016M  Margin of Error!!Nonfamily households!!PERCENT...
255  S1901_C04_016MA  Annotation of Margin of Error!!Nonfamily house...

[256 rows x 2 columns]

In [23]:
df_income

# Keep rows where the part after the underscore in "Variable Code" has 5 characters and ends with 'E'
df_income = df_income[
    df_income["Name"].str.split("_").str[2].str.len() == 4
]
df_income = df_income[
    df_income["Name"].str.split("_").str[2].str.endswith("E")
]

In [26]:
df_income.to_csv(r"D:\UofT\Work\innovo\us_census\reference_files\USE_INCOME_MAPPING_E.csv", index=False)

In [4]:
# All counties in Arkansas
# Download the data from https://api.census.gov/data/timeseries/intltrade/exports/porthsexport?get=group(IT00EXPORTSPORTHS)&E_COMMODITY=-&time=2024-10&CTY_CODE=-&ucgid=0100000US
# https://data.census.gov/table?q=S1901:%20Income%20in%20the%20Past%2012%20Months%20(in%202023%20Inflation-Adjusted%20Dollars)&g=040XX00US01

import requests
import pandas as pd

# Fetch the data
data_url = "https://api.census.gov/data/2023/acs/acs5/subject?get=group(S1901)&ucgid=pseudo(0400000US05$0500000)"

response = requests.get(data_url)

if response.status_code == 200:
    # Extract the data
    data = response.json()

    # Convert to DataFrame for better visualization (optional)
    df_data = pd.DataFrame(data[1:], columns=data[0])

In [5]:
df_data

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001EA,S1901_C01_001M,S1901_C01_001MA,S1901_C01_002E,S1901_C01_002EA,S1901_C01_002M,S1901_C01_002MA,...,S1901_C04_014MA,S1901_C04_015E,S1901_C04_015EA,S1901_C04_015M,S1901_C04_015MA,S1901_C04_016E,S1901_C04_016EA,S1901_C04_016M,S1901_C04_016MA,ucgid
0,0500000US05001,"Arkansas County, Arkansas",6587,None,275,None,5.9,None,2.3,None,...,(X),-888888888,(X),-888888888,(X),39.1,None,-888888888.0,(X),0500000US05001
1,0500000US05003,"Ashley County, Arkansas",7199,None,253,None,10.6,None,3.4,None,...,(X),-888888888,(X),-888888888,(X),64.5,None,-888888888.0,(X),0500000US05003
2,0500000US05005,"Baxter County, Arkansas",19289,None,408,None,4.9,None,1.2,None,...,(X),-888888888,(X),-888888888,(X),33.8,None,-888888888.0,(X),0500000US05005
3,0500000US05007,"Benton County, Arkansas",107667,None,961,None,3.1,None,0.5,None,...,(X),-888888888,(X),-888888888,(X),27.9,None,-888888888.0,(X),0500000US05007
4,0500000US05009,"Boone County, Arkansas",15232,None,363,None,5.1,None,1.5,None,...,(X),-888888888,(X),-888888888,(X),35.4,None,-888888888.0,(X),0500000US05009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0500000US05141,"Van Buren County, Arkansas",7115,None,265,None,7.7,None,2.5,None,...,(X),-888888888,(X),-888888888,(X),31.9,None,-888888888.0,(X),0500000US05141
71,0500000US05143,"Washington County, Arkansas",95467,None,846,None,5.4,None,0.7,None,...,(X),-888888888,(X),-888888888,(X),29.3,None,-888888888.0,(X),0500000US05143
72,0500000US05145,"White County, Arkansas",28945,None,616,None,5.2,None,1.0,None,...,(X),-888888888,(X),-888888888,(X),34.0,None,-888888888.0,(X),0500000US05145
73,0500000US05147,"Woodruff County, Arkansas",2753,None,112,None,8.8,None,2.7,None,...,(X),-888888888,(X),-888888888,(X),41.9,None,-888888888.0,(X),0500000US05147
74,0500000US05149,"Yell County, Arkansas",8053,None,235,None,6.7,None,2.5,None,...,(X),-888888888,(X),-888888888,(X),50.5,None,-888888888.0,(X),0500000US05149